server:
  port: 9999
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/matiz?serverTimezone=UTC
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/matiz?serverTimezone=UTC
      username: root
      password: l1720pq
      driver-class-name: com.mysql.jdbc.Driver
      pool-name: app-hikari-pool
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

